name: Deploy Backend to EC2

on:
  push:
    branches:
      - AWS

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/airline-order-manage:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/airline-order-manage:${{ github.sha }}
            
      - name: Deploy on EC2 via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/airline-cicd
            echo "SPRING_PROFILES_ACTIVE=prod" > .env
            echo "MYSQL_ROOT_PASSWORD=${{ secrets.EC2_MYSQL_ROOT_PASSWORD }}" >> .env
            echo "MYSQL_DATABASE=airline_order_db" >> .env
            echo "MYSQL_USER=${{ secrets.EC2_MYSQL_USER }}" >> .env
            echo "MYSQL_PASSWORD=${{ secrets.EC2_MYSQL_PASSWORD }}" >> .env
            docker-compose pull
            docker-compose down
            docker-compose up -d
